### ISSUE TITLE
UI issue before and after the "0" btn

### ISSUE THREAD

**Issue by Code-Recursion** [Code-Recursion/UI_Calculator#14]
while hovering this issue is trigerred fix it, by makind its display as hidden or some other css tricks

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by Code-Recursion** [comment]
@DevanshCodes sure you can.

**Comment by DevanshCodes** [comment]
Hey @Code-Recursion can you check the PR, it fixes the issue.

**Comment by Code-Recursion** [comment]
Fixed on PR #15
