### ISSUE TITLE
1/0 gives infinity that is wrong.

### ISSUE THREAD

**Issue by Code-Recursion** [Code-Recursion/UI_Calculator#3]
dividing 1 by 0 gives infinity that is wrong.
it should show cannot be divisible by 0
handle this exception using js

**Comment by s-bose** [comment]
Thats what its supposed to do right? Why is that wrong?

**Comment by MatheusMuriel** [comment]
That is correct. Do you want it to display "Invalid operation"?

**Comment by piyushverma001** [comment]
@Code-Recursion  Can I work on it if its still open?

**Comment by piyushverma001** [comment]
@Code-Recursion This issue has been handled in the PR #17 . Kindly review it.
Cheers Happy Hacking!

**Comment by MatheusMuriel** [comment]
I fixed not only division by 0, i fixed all invalid operations like " 158*** " (arithmetics errors)

PR: #18

**Comment by MatheusMuriel** [comment]
@piyushverma001, PR #17 not resolve arithmetics errors

**Comment by Code-Recursion** [comment]
#17
