### ISSUE TITLE
Responsive for mobiles phones

### ISSUE THREAD

**Issue by Code-Recursion** [Code-Recursion/UI_Calculator#4]
![res](https://user-images.githubusercontent.com/52364224/94705069-3e2edd80-035e-11eb-9731-cdc8eab33235.JPG)
Calculator is not alligned properly to the centered Responsive for mobile devices.

**Comment by 1880akshay** [comment]
I want to work on this issue. Please assign this to me!

**Comment by Joshuafolorunsho** [comment]
I am very much interested!

**Comment by 1880akshay** [comment]
@Code-Recursion Have a look at #10

**Comment by pepoflex** [comment]
Please assign me this project, I would love to work on it.

**Comment by Code-Recursion** [comment]
#8  fixed
