### ISSUE TITLE
fix bug in calculator

### ISSUE THREAD

**Issue by Code-Recursion** [Code-Recursion/UI_Calculator#5]
on hovering the buttons before and after "0" are shown up this should be fixed.
![btn](https://user-images.githubusercontent.com/52364224/94704925-13dd2000-035e-11eb-8437-20baf3f8157a.JPG)

**Comment by ibhavikamalhotra** [comment]
I can fix this issue, Assign me .

**Comment by charchitmangal** [comment]
I would Like to work on this Issue

**Comment by AshAman999** [comment]
I can fix this, at least have a look on my work please
fixed the hover issue near zero button

**Comment by Code-Recursion** [comment]
#11  fixed
